export type FieldRecord = { id: string; source: string; speaker: string | null; timestamp: string; original: string | null; location?: { latitude: number; longitude: number } | null; interpretations: { id: string; summary: string; type: string; latitude: number | null; longitude: number | null; location: string | null; confidence: number; spatial_status: string | null }[] };
export type MemberSession = { user: { id: string; name: string; email: string } | null; organizations: { id: string; name: string; role: string }[]; csrf_token: string };
export type WorkspaceData = { modules: string[]; integrations: { devices: { id: string; name: string; enabled: boolean; last_seen_at: string | null; agent_version: string | null }[]; engine: { provider: string; model: string } }; role: string; sites: {id: string; name: string}[]; subscription: { status: string; plan_code: string | null; service_access: string; trial_ends_at: string | null; current_period_end: string | null }; records: FieldRecord[]; actions: { id: string; source_id: string; type: string; reason: string; message: string | null; status: string }[]; messages: { id: string; role: string; content: string }[] };
export async function workspaceRequest<T>(path: string, csrf?: string, payload?: unknown): Promise<T> {
  const response = await fetch(`/api/workspace/${path}`, { method: payload === undefined ? 'GET' : 'POST', credentials: 'same-origin', cache: 'no-store', signal: AbortSignal.timeout(50000), headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(csrf ? { 'X-CSRF-Token': csrf } : {}) }, body: payload === undefined ? undefined : JSON.stringify(payload) });
  const data = await response.json().catch(() => ({ detail: 'The workspace service is unavailable.' }));
  if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : data.error?.message || 'The request could not be completed.');
  return data as T;
}
export const STARTER_MODULES = ['Map', 'Radio Log', 'Observations', 'Satchy'];
