// @vitest-environment node
import { afterEach, expect, it, vi } from 'vitest';
import handler from '../../api/workspace/[...path]';
function response() { return { code: 200, headers: {} as Record<string,string|string[]>, body: undefined as unknown, setHeader(k:string,v:string|string[]){this.headers[k]=v;}, status(code:number){this.code=code;return this;}, json(v:unknown){this.body=v;}, end(v?:string){this.body=v;} }; }
afterEach(() => { delete process.env.TERRASATCH_WORKSPACE_API_URL; vi.unstubAllGlobals(); });
it('fails closed without an explicitly configured workspace API', async () => { const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher); const res=response();await handler({method:'GET',url:'/api/workspace/session',headers:{}},res);expect(res.code).toBe(503);expect(fetcher).not.toHaveBeenCalled(); });
it('rejects cross-origin writes before forwarding a session', async () => { process.env.TERRASATCH_WORKSPACE_API_URL='https://staging.example.com'; const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const res=response(); await handler({method:'POST',url:'/api/workspace/login',headers:{origin:'https://evil.example.com',host:'preview.example.com'},body:{}},res);expect(res.code).toBe(403);expect(fetcher).not.toHaveBeenCalled(); });
it('does not proxy arbitrary API or admin paths', async () => { process.env.TERRASATCH_WORKSPACE_API_URL='https://staging.example.com';const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const res=response();await handler({method:'GET',url:'/api/workspace/admin',headers:{}},res);expect(res.code).toBe(404);expect(fetcher).not.toHaveBeenCalled(); });
it('forwards only member cookie and CSRF to the configured origin and never caches', async () => { process.env.TERRASATCH_WORKSPACE_API_URL='https://staging.example.com';const fetcher=vi.fn().mockResolvedValue({status:200,headers:{getSetCookie:()=>['session=signed; HttpOnly; Secure; SameSite=Lax']},text:async()=>'{"user":null}'});vi.stubGlobal('fetch',fetcher);const res=response();await handler({method:'GET',url:'/api/workspace/session',headers:{cookie:'session=old',authorization:'Bearer do-not-forward'}},res);expect(String(fetcher.mock.calls[0][0])).toBe('https://staging.example.com/api/v1/workspace/session');expect(fetcher.mock.calls[0][1].headers.Authorization).toBeUndefined();expect(res.headers['Cache-Control']).toBe('no-store');expect(res.headers['Set-Cookie']).toEqual(['session=signed; HttpOnly; Secure; SameSite=Lax']); });
