import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import FieldMap from '@/components/FieldMap';
import { workspaceRequest, type MemberSession, type WorkspaceData } from '@/lib/workspace';
import './workspace-preview.css';

export default function Workspace() {
  const [session, setSession] = useState<MemberSession | null>(null);
  const [organization, setOrganization] = useState('');
  const [data, setData] = useState<WorkspaceData | null>(null);
  const [selected, setSelected] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [view, setView] = useState('Map');
  const [noteKey, setNoteKey] = useState(() => crypto.randomUUID());
  const selectRecord = useCallback((id: string) => setSelected(id), []);
  const loadSession = useCallback(async () => {
    const next = await workspaceRequest<MemberSession>('session'); setSession(next);
    setOrganization(current => next.organizations.some(org => org.id === current) ? current : next.organizations[0]?.id || '');
  }, []);
  useEffect(() => { loadSession().catch(e => setError(e.message)); }, [loadSession]);
  const refresh = useCallback(async () => {
    if (!organization) return;
    const next = await workspaceRequest<WorkspaceData>(`organizations/${organization}`);
    setData(next); setSelected(current => next.records.some(r => r.id === current) ? current : next.records[0]?.id || '');
  }, [organization]);
  useEffect(() => { let current = true; setData(null); setSelected(''); if (organization) workspaceRequest<WorkspaceData>(`organizations/${organization}`).then(next => { if (current) { setData(next); setSelected(next.records[0]?.id || ''); } }).catch(e => { if (current) setError(e.message); }); return () => { current = false; }; }, [organization]);
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); } catch(e) { setError(e instanceof Error ? e.message : 'Request failed.'); } finally { setBusy(false); } }
  const record = data?.records.find(r => r.id === selected);
  const canWrite = data && data.role !== 'viewer' && data.subscription.service_access !== 'restricted';
  return <div className="field-workspace min-h-screen bg-background text-foreground">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b p-5"><Link to="/" className="font-display text-xl font-bold">TERRASATCH</Link><span className="text-primary font-display">FIELD WORKSPACE</span>{session?.user && <div className="flex items-center gap-3"><span>{session.user.name}</span><Button variant="outline" disabled={busy} onClick={() => run(async () => { await workspaceRequest('logout', session.csrf_token, {}); setData(null); await loadSession(); })}>Sign out</Button></div>}</header>
    {error && <div role="alert" className="m-5 rounded-lg border border-destructive p-4">{error} <Button variant="link" disabled={busy} onClick={() => run(async () => { await loadSession(); await refresh(); })}>Retry</Button></div>}
    {!session && !error && <p role="status" className="p-6">Connecting to your account…</p>}
    {session && !session.user && <form className="mx-auto my-16 max-w-md space-y-5 p-6 rounded-xl border bg-card" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); run(async () => { await workspaceRequest('login', session.csrf_token, { email: form.get('email'), password: form.get('password') }); await loadSession(); }); }}><h1 className="font-display text-3xl">Take Satchy into your workspace.</h1><p className="text-muted-foreground">Sign in with your activated TerraSatch account.</p><label className="block">Email<Input name="email" type="email" autoComplete="username" required /></label><label className="block">Password<Input name="password" type="password" autoComplete="current-password" required /></label><Button disabled={busy} type="submit">{busy ? 'Signing in…' : 'Sign in'}</Button><p className="text-sm">New account? Follow the activation link sent after signup.</p></form>}
    {session?.user && <><div className="flex flex-wrap justify-between gap-4 p-5 border-b"><label>Workspace <select aria-label="Workspace" className="bg-card border rounded p-2" value={organization} disabled={busy} onChange={e => setOrganization(e.target.value)}>{session.organizations.map(org => <option key={org.id} value={org.id}>{org.name}</option>)}</select></label><span>{data?.subscription.plan_code || 'Account'} · {data?.subscription.status || 'Loading'}</span><Button variant="outline" disabled={busy || !data || !['admin','owner'].includes(data.role)} onClick={() => run(async () => { const result = await workspaceRequest<{url: string}>(`organizations/${organization}/billing`, session.csrf_token, {}); const url = new URL(result.url); if (url.protocol !== 'https:' || url.hostname !== 'billing.stripe.com') throw new Error('Invalid billing destination'); window.location.assign(url.href); })}>Manage billing</Button></div>
    {!organization && <p className="p-6">No active workspace membership is available for this account.</p>}
    {organization && !data && !error && <p role="status" className="p-6">Loading your field records…</p>}
    {data && <div className="workspace-layout"><nav className="workspace-nav p-4 border-b flex flex-wrap xl:flex-col gap-2" aria-label="Workspace views">{['Map','Radio Log','Observations','Workflows','Account'].map(item => <Button key={item} variant={view === item ? 'secondary' : 'ghost'} aria-pressed={view === item} onClick={() => setView(item)}>{item}</Button>)}<Button variant="outline" disabled={busy} onClick={() => run(refresh)}>Refresh records</Button></nav>
    <main className="min-w-0 p-5 space-y-5"><h1 className="text-3xl font-display">{view}</h1><p className="text-sm text-muted-foreground">Latest {data.records.length} records from your workspace.</p>
    {view === 'Map' && <FieldMap records={data.records} onSelect={selectRecord} />}
    {view === 'Account' ? <div className="space-y-3"><p>{session.user.email}</p><p>Your role: {data.role}</p><p>Service access: {data.subscription.service_access}</p><p>Trial ends: {data.subscription.trial_ends_at ? new Date(data.subscription.trial_ends_at).toLocaleDateString() : 'Not in trial'}</p><p>Sites: {data.sites.map(s => s.name).join(', ') || 'No sites configured'}</p></div> : view === 'Workflows' ? <div className="space-y-4">{!data.actions.length && <p>No workflow proposals have been recorded yet.</p>}{data.actions.map(action => <article className="p-4 rounded-lg border space-y-3" key={action.id}><h2 className="font-display text-xl">{action.type.replace(/_/g,' ')}</h2><p>{action.reason}</p>{action.message && <blockquote>{action.message}</blockquote>}<p>Status: {action.status}</p><p className="text-xs break-all">Source: {action.source_id}</p>{action.status === 'awaiting_approval' && canWrite && <div className="flex gap-3"><Button disabled={busy} onClick={() => run(async () => { await workspaceRequest(`organizations/${organization}/actions/${action.id}`, session.csrf_token, {decision:'approve'}); await refresh(); })}>Approve</Button><Button variant="outline" disabled={busy} onClick={() => run(async () => { await workspaceRequest(`organizations/${organization}/actions/${action.id}`, session.csrf_token, {decision:'reject'}); await refresh(); })}>Reject</Button></div>}<p className="text-xs text-muted-foreground">Approval records your decision. It does not claim execution or completion.</p></article>)}</div> : <>
    {canWrite && data.sites.length > 0 && <details className="border rounded-lg p-4"><summary className="cursor-pointer font-display text-xl">Add a field observation</summary><form className="space-y-3 mt-4" onSubmit={e => { e.preventDefault(); const element = e.currentTarget; const fields = new FormData(element); run(async () => { await workspaceRequest(`organizations/${organization}/observations`, session.csrf_token, {site_id: fields.get('site'), request_id: noteKey, text: fields.get('text'), latitude: fields.get('latitude') ? Number(fields.get('latitude')) : null, longitude: fields.get('longitude') ? Number(fields.get('longitude')) : null}); setNoteKey(crypto.randomUUID()); element.reset(); await refresh(); }); }}><label className="block">Site<select name="site" className="block bg-card border p-2 rounded">{data.sites.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="block">Original observation<Textarea name="text" required maxLength={10000} /></label><div className="grid grid-cols-2 gap-3"><label>Latitude (optional)<Input name="latitude" type="number" step="any" min={-90} max={90} /></label><label>Longitude (optional)<Input name="longitude" type="number" step="any" min={-180} max={180} /></label></div><p className="text-xs text-muted-foreground">Coordinates are recorded as supplied by you. Saving preserves your words; it does not invent an AI interpretation.</p><Button type="submit" disabled={busy}>Save observation</Button></form></details>}
    {!data.records.length && <div className="rounded-lg border p-6"><h2 className="font-display text-xl">Your field history starts here.</h2><p>No observations have arrived yet. Records received through your connected TerraSatch sources will appear here.</p></div>}
    <div className="flex gap-2 overflow-x-auto pb-2" aria-label="Recent records">{data.records.map(r => <button className={`rounded border px-3 py-2 shrink-0 text-sm ${r.id === selected ? 'border-primary' : ''}`} key={r.id} aria-pressed={r.id === selected} onClick={() => setSelected(r.id)}>{new Date(r.timestamp).toLocaleString()} · {r.source}</button>)}</div>
    {record && <article className="rounded-lg border bg-card p-5 space-y-5"><div><h2 className="font-display text-xl text-primary">Original input · preserved</h2><blockquote className="text-lg mt-2 whitespace-pre-wrap">{record.original || 'Transcript not available.'}</blockquote><p className="text-sm text-muted-foreground mt-2">{record.source} · {record.speaker || 'Source identity unavailable'} · {new Date(record.timestamp).toLocaleString()}</p></div><div><h3 className="font-display text-xl">Satchy interpretation</h3>{record.interpretations.length ? record.interpretations.map(e => <div className="py-2" key={e.id}><p>{e.summary}</p><p className="text-sm text-muted-foreground">{e.location || 'Location not resolved'} · confidence {Math.round(e.confidence * 100)}%</p></div>) : <p>No interpretation has been recorded.</p>}</div><p className="text-xs break-all">Record {record.id}</p></article>}</>}
    </main><aside id="satchy-panel" className="border-l p-5 space-y-4"><h2 className="font-display text-3xl text-primary">SATCHY</h2><p className="text-sm text-muted-foreground">Ask about your recent field records. Answers are AI interpretations; review the original source before acting.</p><div role="log" aria-label="Satchy conversation" className="space-y-4">{data.messages.map(m => <div key={m.id} className="rounded-lg border p-3"><strong className="text-sm">{m.role === 'user' ? 'You' : 'Satchy'}</strong><p className="whitespace-pre-wrap break-words">{m.content}</p></div>)}</div><form className="space-y-3" onSubmit={e => { e.preventDefault(); run(async () => { await workspaceRequest(`organizations/${organization}/chat`, session.csrf_token, {message}); setMessage(''); await refresh(); }); }}><label htmlFor="satchy-message">Ask Satchy</label><Textarea id="satchy-message" value={message} onChange={e => setMessage(e.target.value)} maxLength={4000} required disabled={!canWrite || busy} /><Button disabled={!canWrite || busy || !message.trim()} type="submit">{busy ? 'Working…' : 'Send to Satchy'}</Button></form><p className="text-xs text-muted-foreground">Chat is private to your account within this workspace. Use Workflows to review recorded action proposals.</p></aside></div>}</>}
  </div>;
}
